      - name: Terraform Plan
        run: terraform plan -out=tfplan.binary

      - name: Generate Plan JSON
        run: terraform show -json tfplan.binary > tfplan.json

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: Environments/test/tfplan.json

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: Run OPA Policy Check
        run: |
          opa eval \
            --fail-defined \
            --format pretty \
            --input tfplan.json \
            --data Policies \
            "data.storage_services.anonymous_access.deny"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan.binary